name: poincare
channels:
- anaconda
- pytorch
- defaults
dependencies:
- pip
- python=3.6
- nltk
- scikit-learn
- pytorch=1.7.0
- pandas=1.1.5
- h5py
- cython
- tqdm
- pip:
  - iopath
  - git+https://github.com/facebookresearch/hypernymysuite.git
